version: '3.9'

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${KEYCLOAK_POSTGRESQL_DB}
      POSTGRES_USER: ${KEYCLOAK_POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_POSTGRESQL_PASS}

  keycloak:
    depends_on:
      - postgres
    container_name: local_keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: ${KEYCLOAK_POSTGRESQL_DB}
      DB_USER: ${KEYCLOAK_POSTGRESQL_USER}
      DB_PASSWORD: ${KEYCLOAK_POSTGRESQL_PASS}
      KEYCLOAK_USER: ${KEYCLOAK_ADMIN}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    image: jboss/keycloak:${KEYCLOAK_VERSION}
    ports:
      - '28080:8080'
    command: -Dkeycloak.profile.feature.upload_scripts=enabled
    restart: unless-stopped

  web-shop-product-service:
    image: patryklanger/product-service:latest
    container_name: productService
    ports:
      - 8082:8082
    expose:
      - 8082
    environment:
      - spring.datasource.url=jdbc:postgresql://productDatabase:5432/${PRODUCT_SERVICE_POSTGRESQL_DB}
      - spring.datasource.username=${PRODUCT_SERVICE_POSTGRESQL_USER}
      - spring.datasource.password=${PRODUCT_SERVICE_POSTGRESQL_PASS}
      - eureka.client.serviceUrl.defaultZone=http://web-shop-discovery:8761/eureka
    depends_on:
      - web-shop-discovery
      - product-database
    links:
      - product-database

  product-database:
    image: postgres:latest
    container_name: productDatabase
    environment:
      POSTGRES_DB: ${PRODUCT_SERVICE_POSTGRESQL_DB}
      POSTGRES_USER: ${PRODUCT_SERVICE_POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${PRODUCT_SERVICE_POSTGRESQL_PASS}
    ports:
      - ${PRODUCT_SERVCIE_POSTGRES_PORT}:5432

  user-database:
    image: postgres:latest
    container_name: userDatabase
    environment:
      POSTGRES_DB: ${AUTH_SERVICE_POSTGRESQL_DB}
      POSTGRES_USER: ${AUTH_SERVICE_POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${AUTH_SERVICE_POSTGRESQL_PASS}
    ports:
      - ${AUTH_SERVICE_POSTGRESQL_PORT}:5432

  web-shop-discovery:
    image: patryklanger/web-shop-discovery:latest
    container_name: web-shop-discovery
    ports:
      - ${DISCOVERY_SERVICE_PORT}:8761

  api-gateway:
    image: patryklanger/web-shop-api-gateway:latest
    container_name: apiGateway
    ports:
      - 8080:8080
    environment:
      - spring.security.oauth2.client.registration.keycloak.client-id=auth-service
      - spring.security.oauth2.client.registration.keycloak.client-secret=1e62797d-9b5f-40e5-9a5e-89e0f1bab6b8
      - spring.security.oauth2.client.provider.keycloak.issuer-uri=http://keycloak:8080/auth/realms/web-shop
      - spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/auth/realms/web-shop/protocol/openid-connect/certs
      - eureka.client.serviceUrl.defaultZone=http://web-shop-discovery:8761/eureka
    depends_on:
      - web-shop-discovery
      - keycloak
    links:
      - keycloak

  order-database:
    image: postgres:latest
    container_name: orderDatabase
    environment:
      POSTGRES_DB: ${ORDER_SERVICE_POSTGRESQL_DB}
      POSTGRES_USER: ${ORDER_SERVICE_POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${ORDER_SERVICE_POSTGRESQL_PASS}
    ports:
      - 5555:5432

  order-service:
    image: patryklanger/order-service:latest
    container_name: orderService
    ports:
      - 8090:8090
    environment:
      - spring.security.oauth2.client.registration.keycloak.client-id=auth-service
      - spring.security.oauth2.client.registration.keycloak.client-secret=1e62797d-9b5f-40e5-9a5e-89e0f1bab6b8
      - spring.security.oauth2.client.provider.keycloak.issuer-uri=http://keycloak:8080/auth/realms/web-shop
      - spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/auth/realms/web-shop/protocol/openid-connect/certs
      - eureka.client.serviceUrl.defaultZone=http://web-shop-discovery:8761/eureka
      - spring.datasource.url=jdbc:postgresql://orderDatabase:5432/${ORDER_SERVICE_POSTGRESQL_DB}
      - spring.datasource.username=${ORDER_SERVICE_POSTGRESQL_USER}
      - spring.datasource.password=${ORDER_SERVICE_POSTGRESQL_PASS}
      - app.product-service.buy-url=http://web-shop-product-service:8082/api/products/product/buy
    depends_on:
      - web-shop-discovery
      - order-database
      - keycloak
      - web-shop-product-service
    links:
      - keycloak
      - web-shop-product-service

  web-shop-auth-service:
    image: patryklanger/web-shop-auth-service:latest
    container_name: authService
    ports:
      - 8085:8085
    environment:
      - spring.datasource.url=jdbc:postgresql://userDatabase:5432/${AUTH_SERVICE_POSTGRESQL_DB}
      - spring.datasource.username=${AUTH_SERVICE_POSTGRESQL_USER}
      - spring.datasource.password=${AUTH_SERVICE_POSTGRESQL_PASS}
      - eureka.client.serviceUrl.defaultZone=http://web-shop-discovery:8761/eureka
      - keycloak.auth-server-url=http://keycloak:8080/auth
      - app.keycloak.login.url=http://keycloak:8080/auth/realms/web-shop/protocol/openid-connect/token
      - app.keycloak.user.url=http://keycloak:8080/admin/realms/web-shop/users
    depends_on:
      - web-shop-discovery
      - user-database
    links:
      - user-database
