version: '3.9'

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${KEYCLOAK_POSTGRESQL_DB}
      POSTGRES_USER: ${KEYCLOAK_POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_POSTGRESQL_PASS}
    networks:
      - local-keycloak

  keycloak:
    depends_on:
      - postgres
    container_name: local_keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: ${KEYCLOAK_POSTGRESQL_DB}
      DB_USER: ${KEYCLOAK_POSTGRESQL_USER}
      DB_PASSWORD: ${KEYCLOAK_POSTGRESQL_PASS}
      KEYCLOAK_USER: ${KEYCLOAK_ADMIN}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    image: jboss/keycloak:${KEYCLOAK_VERSION}
    ports:
      - '28080:8080'
    command: -Dkeycloak.profile.feature.upload_scripts=enabled
    restart: unless-stopped
    networks:
      - local-keycloak

  product-database:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${PRODUCT_SERVICE_POSTGRESQL_DB}
      POSTGRES_USER: ${PRODUCT_SERVICE_POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${PRODUCT_SERVICE_POSTGRESQL_PASS}
    ports:
      - ${PRODUCT_SERVCIE_POSTGRES_PORT}:5432
    networks:
      - product-service

  user-database:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${AUTH_SERVICE_POSTGRESQL_DB}
      POSTGRES_USER: ${AUTH_SERVICE_POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${AUTH_SERVICE_POSTGRESQL_PASS}
    ports:
      - ${AUTH_SERVICE_POSTGRESQL_PORT}:5432
    networks:
      - auth-service
  
  web-shop-discovery:
    image: patryklanger/web-shop-discovery:latest
    ports:
      - ${DISCOVERY_SERVICE_PORT}:8761

  web-shop-product-service:
    image: patryklanger/web-shop-product-service:latest
    ports:
      - 8082:8082
    links:
      - product-database
    networks:
      - product-service


networks:
  local-keycloak:
  product-service:
  auth-service:
